import shlex
import subprocess
import sys
from argparse import Namespace
from pathlib import Path

import mdq


def handle(options: Namespace) -> None:
    if not Path("/run/systemd/system").exists():
        raise ValueError("Host appears not to use systemd")

    dest = Path.home() / ".config" / "systemd" / "user" / "mdq.service"
    with mdq.console.status(f"Creating unit file {dest}"):
        if dest.exists() and not options.force:
            raise FileExistsError(str(dest))

        dest.parent.mkdir(parents=True, exist_ok=True)

        # Default setup: dummy query, k=0, default extensions in current (at
        # time of running `mdq systemd`) working directory
        exec_cmd = shlex.join(
            [sys.executable, "-m", "mdq", "-q", "dummy", "-k", "0"],
        )
        body = f"""\
# Autogenerated by {__file__}
dest
[Unit]
Description=Run dummy mdq query to populate cache

[Service]
Type=oneshot
WorkingDirectory={str(Path().absolute())}
ExecStart={exec_cmd}

[Install]
WantedBy=default.target
"""
        dest.write_text(body)

    cmd = ["systemctl", "--user", "daemon-reload"]
    with mdq.console.status(shlex.join(cmd)):
        subprocess.run(cmd).check_returncode()

    cmd = ["systemctl", "--user", "enable", "--now", "mdq"]
    with mdq.console.status(shlex.join(cmd)):
        subprocess.run(cmd).check_returncode()
